create table if not exists public."UsersProfile" (
  id bigint generated by default as identity primary key,
  owner_id uuid not null unique references auth.users(id) on delete cascade,
  username text not null,
  "displayName" text,
  email text not null unique,
  phone numeric,
  "carModel" text not null,
  "carPlate" text not null unique,
  "pictureUrl" text,
  available boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public."Trips" (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  customer_id text,
  name text not null,
  address text,
  pickup text,
  destination text,
  passenger_phone text,
  preferred_time text,
  price numeric(12, 2) check (price is null or price >= 0),
  done text not null default 'pending' check (done in ('pending', 'completed', 'cancelled')),
  done_by_customer boolean,
  created_at timestamptz not null default now()
);

create index if not exists trips_owner_id_idx on public."Trips" (owner_id);
create index if not exists trips_customer_id_created_at_idx on public."Trips" (customer_id, created_at desc);

create table if not exists public."Expenses" (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  type text not null,
  amount numeric(12, 2) not null check (amount >= 0),
  date date not null default current_date,
  created_at timestamp without time zone default (now() at time zone 'utc')
);

create index if not exists expenses_owner_id_idx on public."Expenses" (owner_id);

create table if not exists public.usersettings (
  id bigint generated by default as identity primary key,
  owner_id uuid not null unique references auth.users(id) on delete cascade,
  gas_unit_cost numeric default 50,
  insurance_monthly numeric default 100,
  registration_monthly numeric default 50,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.payments (
  id bigint generated by default as identity primary key,
  trip_id bigint references public."Trips"(id) on delete set null,
  owner_id uuid references public."UsersProfile"(owner_id) on delete set null,
  customer_id text,
  client_id uuid default auth.uid(),
  topic text,
  mp_payment_id text not null unique,
  amount numeric(12, 2),
  status text,
  raw_query jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists payments_owner_id_idx on public.payments (owner_id);
create index if not exists payments_trip_id_idx on public.payments (trip_id);

alter table public."UsersProfile" enable row level security;
alter table public."Trips" enable row level security;
alter table public."Expenses" enable row level security;
alter table public.usersettings enable row level security;
alter table public.payments enable row level security;

create policy "drivers read own profile" on public."UsersProfile"
  for select to authenticated using (auth.uid() = owner_id);
create policy "drivers insert own profile" on public."UsersProfile"
  for insert to authenticated with check (auth.uid() = owner_id);
create policy "drivers update own profile" on public."UsersProfile"
  for update to authenticated using (auth.uid() = owner_id) with check (auth.uid() = owner_id);

create policy "drivers read own trips" on public."Trips"
  for select to authenticated using (auth.uid() = owner_id);
create policy "drivers insert own trips" on public."Trips"
  for insert to authenticated with check (auth.uid() = owner_id and customer_id is null);
create policy "drivers update own trips" on public."Trips"
  for update to authenticated using (auth.uid() = owner_id) with check (auth.uid() = owner_id);

create policy "drivers read own expenses" on public."Expenses"
  for select to authenticated using (auth.uid() = owner_id);
create policy "drivers insert own expenses" on public."Expenses"
  for insert to authenticated with check (auth.uid() = owner_id);
create policy "drivers update own expenses" on public."Expenses"
  for update to authenticated using (auth.uid() = owner_id) with check (auth.uid() = owner_id);
create policy "drivers delete own expenses" on public."Expenses"
  for delete to authenticated using (auth.uid() = owner_id);

create policy "drivers read own settings" on public.usersettings
  for select to authenticated using ((select auth.uid()) = owner_id);
create policy "drivers insert own settings" on public.usersettings
  for insert to authenticated with check ((select auth.uid()) = owner_id);
create policy "drivers update own settings" on public.usersettings
  for update to authenticated
  using ((select auth.uid()) = owner_id)
  with check ((select auth.uid()) = owner_id);

create policy "drivers read own payments" on public.payments
  for select to authenticated using (auth.uid() = owner_id);

create or replace function public.list_available_drivers()
returns table (
  id bigint,
  owner_id uuid,
  username text,
  "displayName" text,
  "carModel" text,
  "carPlate" text,
  "pictureUrl" text,
  available boolean,
  created_at timestamptz
)
language sql
security definer
set search_path = ''
stable
as $$
  select p.id, p.owner_id, p.username, p."displayName", p."carModel", p."carPlate",
         p."pictureUrl", coalesce(p.available, false), p.created_at
  from public."UsersProfile" p
  where coalesce(p.available, false) = true
  order by p.created_at desc;
$$;

create or replace function public.request_trip(
  p_customer_id text,
  p_owner_id uuid,
  p_name text,
  p_pickup text,
  p_destination text,
  p_passenger_phone text default null,
  p_preferred_time text default null
)
returns table (trip_id bigint, created_at timestamptz)
language plpgsql
security definer
set search_path = public
as $$
declare
  inserted_trip public."Trips";
begin
  if length(trim(p_customer_id)) < 32 then
    raise exception 'Invalid customer identifier';
  end if;
  if nullif(trim(p_name), '') is null or nullif(trim(p_pickup), '') is null or nullif(trim(p_destination), '') is null then
    raise exception 'Name, pickup and destination are required';
  end if;
  if not exists (
    select 1 from public."UsersProfile"
    where owner_id = p_owner_id and available = true
  ) then
    raise exception 'Driver is not available';
  end if;

  insert into public."Trips" (
    owner_id, customer_id, name, pickup, destination, passenger_phone, preferred_time, done
  ) values (
    p_owner_id, p_customer_id, trim(p_name), trim(p_pickup), trim(p_destination),
    nullif(trim(p_passenger_phone), ''), nullif(trim(p_preferred_time), ''), 'pending'
  ) returning * into inserted_trip;

  return query select inserted_trip.id, inserted_trip.created_at;
end;
$$;

create or replace function public.get_customer_last_trip(p_customer_id text)
returns table (
  trip_id bigint,
  done text,
  created_at timestamptz,
  owner_id uuid,
  pickup text,
  destination text,
  preferred_time text,
  price numeric,
  driver_name text,
  driver_available boolean
)
language sql
security definer
set search_path = public
stable
as $$
  select t.id, t.done, t.created_at, t.owner_id, t.pickup, t.destination,
         t.preferred_time, t.price,
         coalesce(p."displayName", p.username, 'Conductor') as driver_name,
         p.available as driver_available
  from public."Trips" t
  join public."UsersProfile" p on p.owner_id = t.owner_id
  where t.customer_id = p_customer_id and length(trim(p_customer_id)) >= 32
  order by t.created_at desc
  limit 1;
$$;

create or replace function public.get_payment_result(p_payment_id text)
returns table (amount numeric, status text, mp_payment_id text)
language sql
security definer
set search_path = public
stable
as $$
  select p.amount, p.status, p.mp_payment_id
  from public.payments p
  where p.mp_payment_id = p_payment_id
  limit 1;
$$;

revoke all on public."UsersProfile", public."Trips", public."Expenses", public.usersettings, public.payments from anon;
grant select, insert, update on public."UsersProfile", public."Trips", public."Expenses" to authenticated;
grant delete on public."Expenses" to authenticated;
grant select, insert, update on public.usersettings to authenticated;
grant select on public.payments to authenticated;

revoke all on function public.list_available_drivers() from public;
revoke all on function public.request_trip(text, uuid, text, text, text, text, text) from public;
revoke all on function public.get_customer_last_trip(text) from public;
revoke all on function public.get_payment_result(text) from public;
grant execute on function public.list_available_drivers() to anon, authenticated;
grant execute on function public.request_trip(text, uuid, text, text, text, text, text) to anon, authenticated;
grant execute on function public.get_customer_last_trip(text) to anon, authenticated;
grant execute on function public.get_payment_result(text) to anon, authenticated;

grant usage, select on all sequences in schema public to authenticated;
