-- Reconcile the legacy production database with the versioned schema.
-- Direct anonymous table access is intentionally removed: the customer flow
-- uses the explicitly granted RPCs below.

create table if not exists public.usersettings (
  id bigint generated by default as identity primary key,
  owner_id uuid not null unique references auth.users(id) on delete cascade,
  gas_unit_cost numeric default 50,
  insurance_monthly numeric default 100,
  registration_monthly numeric default 50,
  created_at timestamptz not null default timezone('utc', now())
);

alter table public."Trips" add column if not exists address text;
alter table public."Trips" add column if not exists done_by_customer boolean;
alter table public."Expenses" add column if not exists created_at timestamp without time zone default (now() at time zone 'utc');
alter table public.payments add column if not exists trip_id bigint;
alter table public.payments add column if not exists customer_id text;
alter table public.payments add column if not exists client_id uuid default auth.uid();
alter table public.payments add column if not exists topic text;
alter table public.payments add column if not exists amount numeric(12, 2);
alter table public.payments add column if not exists status text;
alter table public.payments add column if not exists updated_at timestamptz not null default now();

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conrelid = 'public.payments'::regclass
      and conname = 'payments_trip_id_fkey'
  ) then
    alter table public.payments
      add constraint payments_trip_id_fkey
      foreign key (trip_id) references public."Trips"(id) on delete set null;
  end if;
end
$$;

alter table public."UsersProfile" enable row level security;
alter table public."Trips" enable row level security;
alter table public."Expenses" enable row level security;
alter table public.usersettings enable row level security;
alter table public.payments enable row level security;
alter table public.customer_profiles enable row level security;

-- Remove legacy/global policies before installing one policy per operation.
drop policy if exists "Allow anon select on Trips" on public."Trips";
drop policy if exists "Anonymous users can create pending trips" on public."Trips";
drop policy if exists "Anonymous users can read pending trips" on public."Trips";
drop policy if exists "Anonymous users can update pending trips" on public."Trips";
drop policy if exists "Users can only access their own trips" on public."Trips";
drop policy if exists "drivers read own trips" on public."Trips";
drop policy if exists "drivers insert own trips" on public."Trips";
drop policy if exists "drivers update own trips" on public."Trips";

create policy "drivers read own trips" on public."Trips"
  for select to authenticated
  using ((select auth.uid()) = owner_id);
create policy "drivers insert own trips" on public."Trips"
  for insert to authenticated
  with check ((select auth.uid()) = owner_id);
create policy "drivers update own trips" on public."Trips"
  for update to authenticated
  using ((select auth.uid()) = owner_id)
  with check ((select auth.uid()) = owner_id);

drop policy if exists "Policy with security definer functions" on public."Expenses";
drop policy if exists "drivers read own expenses" on public."Expenses";
drop policy if exists "drivers insert own expenses" on public."Expenses";
drop policy if exists "drivers update own expenses" on public."Expenses";
drop policy if exists "drivers delete own expenses" on public."Expenses";

create policy "drivers read own expenses" on public."Expenses"
  for select to authenticated
  using ((select auth.uid()) = owner_id);
create policy "drivers insert own expenses" on public."Expenses"
  for insert to authenticated
  with check ((select auth.uid()) = owner_id);
create policy "drivers update own expenses" on public."Expenses"
  for update to authenticated
  using ((select auth.uid()) = owner_id)
  with check ((select auth.uid()) = owner_id);
create policy "drivers delete own expenses" on public."Expenses"
  for delete to authenticated
  using ((select auth.uid()) = owner_id);

drop policy if exists "drivers read own profile" on public."UsersProfile";
drop policy if exists "drivers insert own profile" on public."UsersProfile";
drop policy if exists "drivers update own profile" on public."UsersProfile";

create policy "drivers read own profile" on public."UsersProfile"
  for select to authenticated
  using ((select auth.uid()) = owner_id);
create policy "drivers update own profile" on public."UsersProfile"
  for update to authenticated
  using ((select auth.uid()) = owner_id)
  with check ((select auth.uid()) = owner_id);

drop policy if exists "drivers read own settings" on public.usersettings;
drop policy if exists "drivers insert own settings" on public.usersettings;
drop policy if exists "drivers update own settings" on public.usersettings;

create policy "drivers read own settings" on public.usersettings
  for select to authenticated
  using ((select auth.uid()) = owner_id);
create policy "drivers insert own settings" on public.usersettings
  for insert to authenticated
  with check ((select auth.uid()) = owner_id);
create policy "drivers update own settings" on public.usersettings
  for update to authenticated
  using ((select auth.uid()) = owner_id)
  with check ((select auth.uid()) = owner_id);

drop policy if exists "customers read own profile" on public.customer_profiles;
drop policy if exists "customers insert own profile" on public.customer_profiles;
drop policy if exists "customers update own profile" on public.customer_profiles;

create policy "customers read own profile" on public.customer_profiles
  for select to authenticated
  using ((select auth.uid()) = user_id);
create policy "customers insert own profile" on public.customer_profiles
  for insert to authenticated
  with check ((select auth.uid()) = user_id);
create policy "customers update own profile" on public.customer_profiles
  for update to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

drop policy if exists "Allow service_role full access" on public.payments;
drop policy if exists "drivers read own payments" on public.payments;

-- Data API grants: anonymous users call narrow RPCs and never tables directly.
revoke all privileges on table public."UsersProfile" from anon, authenticated;
revoke all privileges on table public."Trips" from anon, authenticated;
revoke all privileges on table public."Expenses" from anon, authenticated;
revoke all privileges on table public.usersettings from anon, authenticated;
revoke all privileges on table public.payments from anon, authenticated;
revoke all privileges on table public.customer_profiles from anon, authenticated;

grant select, update on table public."UsersProfile" to authenticated;
grant select, insert, update on table public."Trips" to authenticated;
grant select, insert, update, delete on table public."Expenses" to authenticated;
grant select, insert, update on table public.usersettings to authenticated;
grant select, insert, update on table public.customer_profiles to authenticated;

revoke all privileges on all sequences in schema public from anon, authenticated;
grant usage, select on sequence public."Trips_id_seq" to authenticated;
grant usage, select on sequence public."Expenses_id_seq" to authenticated;
grant usage, select on sequence public.usersettings_id_seq to authenticated;

-- Opt in to the new least-privilege defaults for future public objects.
alter default privileges for role postgres in schema public
  revoke select, insert, update, delete on tables from anon, authenticated;
alter default privileges for role postgres in schema public
  revoke usage, select on sequences from anon, authenticated;
alter default privileges for role postgres in schema public
  revoke execute on functions from public, anon, authenticated;

create index if not exists trips_owner_id_idx on public."Trips" (owner_id);
create index if not exists trips_customer_id_created_at_idx on public."Trips" (customer_id, created_at desc);
create index if not exists expenses_owner_id_idx on public."Expenses" (owner_id);
create index if not exists payments_owner_id_idx on public.payments (owner_id);
create index if not exists payments_trip_id_idx on public.payments (trip_id);

create or replace function public.get_payment_result(p_payment_id text)
returns table (amount numeric, status text, mp_payment_id text)
language sql
stable
security definer
set search_path = ''
as $$
  select p.amount, p.status, p.mp_payment_id
  from public.payments as p
  where p.mp_payment_id = nullif(trim(p_payment_id), '')
  limit 1;
$$;

revoke all on function public.list_available_drivers() from public, anon, authenticated;
revoke all on function public.request_trip(text, uuid, text, text, text, text, text) from public, anon, authenticated;
revoke all on function public.get_customer_last_trip(text) from public, anon, authenticated;
revoke all on function public.get_payment_result(text) from public, anon, authenticated;

grant execute on function public.list_available_drivers() to anon, authenticated;
grant execute on function public.request_trip(text, uuid, text, text, text, text, text) to anon, authenticated;
grant execute on function public.get_customer_last_trip(text) to anon, authenticated;
grant execute on function public.get_payment_result(text) to anon, authenticated;

notify pgrst, 'reload schema';
